# Generated by Django 3.2.8 on 2021-10-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=15)),
                ('from_currency_name', models.CharField(max_length=50)),
                ('to_currency_code', models.CharField(max_length=15)),
                ('to_currency_name', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('last_refreshed_time', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=15)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'db_table': 'exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=15)),
                ('from_currency_name', models.CharField(max_length=50)),
                ('to_currency_code', models.CharField(max_length=15)),
                ('to_currency_name', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('last_refreshed_time', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=15)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'db_table': 'exchange_rate_log',
            },
        ),
    ]
